<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;

class RoleSeeder extends Seeder
{
    public function run()
    {
        // Reset cached roles and permissions
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        // List of roles and their permissions
        $roles = [
            'Requester' => ['Submit Request Forms', 'Access User Dashboard', 'View All Request Forms', 'View Submitted Request Forms', 'Check Request Status'],
            // 'HR Officer' => ['Approve Head of Department Requests', 'Approve HR Requests', 'Submit Request Forms', 'Access User Dashboard', 'View All Request Forms', 'View Submitted Request Forms', 'Check Request Status'],
            'HR Manager' => ['Approve HR Requests', 'Approve Head of Department Requests', 'Submit Request Forms', 'Access User Dashboard', 'View All Request Forms', 'View Submitted Request Forms', 'Check Request Status', 'Manage Employee Information'],
            'Admin' => ['Approve IT Requests', 'Approve HR Requests', 'Submit Request Forms', 'Access User Dashboard', 'View All Request Forms', 'View Submitted Request Forms', 'Check Request Status'],
            'Line Manager' => ['Approve Head of Department Requests', 'Submit Request Forms', 'Access User Dashboard', 'View All Request Forms', 'View Submitted Request Forms', 'Check Request Status'],
            'finance officer' => ['Approve Head of Department Requests', 'Submit Request Forms', 'Access User Dashboard', 'View All Request Forms', 'View Submitted Request Forms', 'Check Request Status'],

            'Acting Line Manager' => ['Approve Head of Department Requests', 'Submit Request Forms', 'Access User Dashboard', 'View All Request Forms', 'View Submitted Request Forms', 'Check Request Status'],
            'Super Admin' => ['Submit Request Forms', 'Access User Dashboard', 'View All Request Forms', 'View Submitted Request Forms', 'Check Request Status', 'Approve HR Requests', 'Approve IT Requests', 'Approve Head of Department Requests', 'Assign Roles to Users', 'Assign Permissions to Roles', 'View Existing Roles', 'Create New Roles', 'Edit Existing Roles', 'Delete Roles'],
            'Executive' => ['Approve Head of Department Requests', 'Submit Request Forms', 'Access User Dashboard', 'View All Request Forms', 'View Submitted Request Forms', 'Check Request Status'],
        ];

        // Define roles and assign existing permissions
        $roles = [
            'Super-Admin' => [
                'view dashboard',
                'view forms',
                'view ict access form',
                'view hr clearance form',
                'view data security agreement',
                'view change management',
                'view requests',
                'view my requests',
                'approve requests',
                'view general requests',
                'approve general requests',
                'view departments',
                'view nhif',
                'view hmis',
                'view remarks',
                'view user category',
                'view employment type',
                'manage users',
                'edit users',
                'delete users',
                'activate users',
                'deactivate users',
                'reset user password',
                'assign user roles',
                'assign roles',
                'manage roles',
                'assign permissions',
                'manage permissions',
                'view settings',
                'view logs',
                'view oncall requests',
                'create oncall requests',
                'edit oncall requests',
                'delete oncall requests',
                'approve oncall requests',
                'reject oncall requests',
                'view oncall reports',
                'view oncall settings',
                'manage oncall settings',
                'view locum requests',
                'create locum requests',
                'edit locum requests',
                'delete locum requests',
                'approve locum requests',
                'reject locum requests',
                'view locum reports',
                'view locum settings',
                'manage locum settings',
                'view hr forms',
                'view it requests',
                'create it requests',
                'view staff details',
                'view employee details',
                'edit employee details',
                'view employee forms',
                'view biometric attendance',
                'manage biometric attendance',
                'view contracts',
                'view vendors',
                'view entities',
                'view procureents',
                'view announcements',
                'view policies',
                'view sops',
                'manage maintenance mode',
                'view sap access',
                'approve forms',
                'reject forms',
                'view form details',
                'edit forms',
                'delete forms',
                'manage change request categories',
                'view signatures',
                'manage signatures',
                'approve signatures',
                'reject signatures',
                'manage platforms',
                'manage units',
                'assign platform managers',
                'assign unit incharge',
                'view hr documents',
                'upload hr documents',
                'delete hr documents',
                'download hr documents',
                'view id card requests',
                'create id card requests',
                'view clearance forms',
                'create clearance forms',
                'approve clearance forms',
                'reject clearance forms',
                'access bank details form',
                'access heslb form',
                'access nhif registration',
                'access clearance form',
                'access requisitions form',
                'access other documents',
            ],
            'admin' => [
                'view dashboard',
                'view forms',
                'view ict access form',
                'view hr clearance form',
                'view data security agreement',
                'view change management',
                'view requests',
                'view my requests',
                'approve requests',
                'view general requests',
                'approve general requests',
                'view departments',
                'view nhif',
                'view hmis',
                'view remarks',
                'view user category',
                'view employment type',
                'manage users',
                'assign roles',
                'manage roles',
                'assign permissions',
                'manage permissions',
                'view settings',
                'view logs',
                'view oncall requests',
                'create oncall requests',
                'edit oncall requests',
                'delete oncall requests',
                'approve oncall requests',
                'reject oncall requests',
                'view oncall reports',
                'view oncall settings',
                'manage oncall settings',
                'view locum requests',
                'create locum requests',
                'edit locum requests',
                'delete locum requests',
                'approve locum requests',
                'reject locum requests',
                'view locum reports',
                'view locum settings',
                'manage locum settings',
                'view hr forms',
                'view it requests',
                'create it requests',
                'view staff details',
                'view employee details',
                'view biometric attendance',
                'manage biometric attendance',
                'view contracts',
                'view vendors',
                'view entities',
                'view procureents',
                'view announcements',
                'view policies',
                'view sops',
                'manage maintenance mode',
                'view sap access',
            ],
            'hr' => [
                'view dashboard',
                'view forms',
                'view requests',
                'view my requests',
                'approve requests',
                'view general requests',
                'approve general requests',
                'view oncall requests',
                'approve oncall requests',
                'reject oncall requests',
                'view oncall reports',
                'view oncall settings',
                'manage oncall settings',
                'view locum requests',
                'approve locum requests',
                'reject locum requests',
                'view locum reports',
                'view locum settings',
                'manage locum settings',
                'view hr forms',
                'view staff details',
                'view employee details',
                'edit employee details',
                'view employee forms',
                'view biometric attendance',
                'view announcements',
                'view policies',
                'view sops',
                'view logs',
                'manage maintenance mode',
                'manage users',
                'edit users',
                'activate users',
                'deactivate users',
                'reset user password',
                'approve forms',
                'reject forms',
                'view form details',
                'view signatures',
                'approve signatures',
                'reject signatures',
                'view hr documents',
                'upload hr documents',
                'delete hr documents',
                'download hr documents',
                'view clearance forms',
                'approve clearance forms',
                'reject clearance forms',
                'access bank details form',
                'access heslb form',
                'access nhif registration',
                'access clearance form',
                'access requisitions form',
            ],
            'it' => [
                'view dashboard',
                'view forms',
                'view ict access form',
                'approve requests',
                'view general requests',
                'approve general requests',
                'view departments',
                'view user category',
                'view requests',
                'view my requests',
                'view oncall requests',
                'view locum requests',
                'view hr forms',
                'view it requests',
                'create it requests',
                'view staff details',
                'view biometric attendance',
                'view announcements',
                'view change management',
                'approve forms',
                'reject forms',
                'manage change request categories',
            ],
            'line-manager' => [
                'view dashboard',
                'view forms',
                'view requests',
                'view my requests',
                'approve requests',
                'view general requests',
                'approve general requests',
                'view departments',
                'view user category',
                'view oncall requests',
                'create oncall requests',
                'edit oncall requests',
                'approve oncall requests',
                'reject oncall requests',
                'view locum requests',
                'create locum requests',
                'edit locum requests',
                'approve locum requests',
                'reject locum requests',
                'view hr forms',
                'view it requests',
                'create it requests',
                'view ict access form',
                'view form details',
                'view biometric attendance',
                'view announcements',
                'view policies',
                'view sops',
                'view change management',
                'approve forms',
                'reject forms',
            ],
            'acting-line-manager' => [
                'view dashboard',
                'view forms',
                'approve requests',
                'view departments',
                'view user category',
                'view oncall requests',
                'create oncall requests',
                'approve oncall requests',
                'reject oncall requests',
                'view locum requests',
                'create locum requests',
                'approve locum requests',
                'reject locum requests',
                'view hr forms',
            ],
            'finance officer' => [
                'view dashboard',
                'view forms',
                'approve requests',
                'view departments',
                'view user category',
                'view oncall requests',
                'view locum requests',
                'view hr forms',
            ],
            'requester' => [
                'view dashboard',
                'view forms',
                'view requests',
                'view my requests',
                'view oncall requests',
                'create oncall requests',
                'edit oncall requests',
                'view locum requests',
                'create locum requests',
                'edit locum requests',
                'view hr forms',
                'view it requests',
                'create it requests',
                'view announcements',
                'view change management',
            ],
            'coo' => [
                'view dashboard',
                'view forms',
                'view requests',
                'view my requests',
                'approve requests',
                'view general requests',
                'approve general requests',
                'view oncall requests',
                'approve oncall requests',
                'reject oncall requests',
                'view locum requests',
                'approve locum requests',
                'reject locum requests',
                'view hr forms',
                'view announcements',
                'view policies',
                'view sops',
                'view change management',
                'approve forms',
                'reject forms',
            ],
            'cfo' => [
                'view dashboard',
                'view forms',
                'view requests',
                'view my requests',
                'approve requests',
                'view general requests',
                'approve general requests',
                'view oncall requests',
                'approve oncall requests',
                'reject oncall requests',
                'view locum requests',
                'approve locum requests',
                'reject locum requests',
                'view hr forms',
                'view announcements',
                'view policies',
                'view sops',
                'view change management',
                'approve forms',
                'reject forms',
            ],
            'cms' => [
                'view dashboard',
                'view forms',
                'view requests',
                'view my requests',
                'approve requests',
                'view general requests',
                'approve general requests',
                'view oncall requests',
                'approve oncall requests',
                'reject oncall requests',
                'view locum requests',
                'approve locum requests',
                'reject locum requests',
                'view hr forms',
                'view announcements',
                'view policies',
                'view sops',
                'view change management',
                'approve forms',
                'reject forms',
            ],
            'crhdo' => [
                'view dashboard',
                'view forms',
                'view requests',
                'view my requests',
                'approve requests',
                'view general requests',
                'approve general requests',
                'view oncall requests',
                'approve oncall requests',
                'reject oncall requests',
                'view locum requests',
                'approve locum requests',
                'reject locum requests',
                'view hr forms',
                'view announcements',
                'view change management',
                'approve forms',
                'reject forms',
            ],
            'in-charge' => [
                'view dashboard',
                'view forms',
                'view requests',
                'view my requests',
                'view oncall requests',
                'create oncall requests',
                'view locum requests',
                'create locum requests',
                'view hr forms',
                'view it requests',
                'create it requests',
                'view announcements',
                'view change management',
            ],
        ];

        // Create roles and assign permissions
        foreach ($roles as $roleName => $permissions) {
            $role = Role::firstOrCreate(['name' => $roleName]);
            if (!empty($permissions)) {
                $role->syncPermissions($permissions);
            }
        }
    }
}
